import 'package:mobx/mobx.dart';
import 'package:json_annotation/json_annotation.dart';
import '../game_component.dart';
import '../component_registry.dart';

part 'game_object.g.dart';

Map<String, dynamic> _componentsToJson(List<GameComponent>? comps) {
  final map = <String, dynamic>{};
  if (comps == null) return map;
  for (final c in comps) {
    map[c.id] = c.toJson();
  }
  return map;
}

List<GameComponent> _componentsFromJson(Map<String, dynamic>? map) {
  final comps = <GameComponent>[];
  if (map == null) return comps;
  map.forEach((typeId, data) {
    try {
      final c = ComponentRegistry.create(typeId, data as Map<String, dynamic>);
      comps.add(c);
    } catch (_) {}
  });
  return comps;
}

@JsonSerializable(explicitToJson: true)
class GameObject {
  final String id;
  String name;
  String? parentId;

  /// A única fonte de verdade: lista de componentes
  @JsonKey(fromJson: _componentsFromJson, toJson: _componentsToJson)
  final List<GameComponent> components;

  /// Observable children list so MobX observers detect add/remove
  final ObservableList<GameObject> children;

  GameObject({
    required this.id,
    required this.name,
    this.parentId,
    Map<String, String>? tags,
    List<GameComponent>? components,
    List<GameObject>? children,
  })  : components = components ?? [],
        children = ObservableList.of(children ?? []) {
  }

  // --- Component helpers ---
  T? getComponent<T extends GameComponent>() {
    for (final c in components) {
      if (c is T) return c;
    }
    return null;
  }

  GameComponent? getComponentById(String id) {
    try {
      return components.firstWhere((c) => c.id == id);
    } catch (_) {
      return null;
    }
  }

  void setComponent<T extends GameComponent>(T component) {
    components.removeWhere((c) => c.id == component.id);
    components.add(component);
  }

  /// Return a new GameObject with the given component replaced/added (immutable helper)
  GameObject copyWithComponent(GameComponent newComponent) {
    final newComponents = List<GameComponent>.from(components);
    
    final index = newComponents.indexWhere((c) => c.id == newComponent.id);

    if (index != -1) {
      newComponents[index] = newComponent;
    } else {
      newComponents.add(newComponent);
    }

    return GameObject(
      id: id,
      name: name,
      parentId: parentId,
      components: newComponents,
      children: children,
    );
  }

  void addChild(GameObject child) {
    child.parentId = id;
    children.add(child);
  }

  void removeChild(String childId) {
    children.removeWhere((c) => c.id == childId);
  }

  // JSON serialization generated by json_serializable
  factory GameObject.fromJson(Map<String, dynamic> json) => _$GameObjectFromJson(json);
  Map<String, dynamic> toJson() => _$GameObjectToJson(this);
}
