name: Build and Release O3M

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - os: windows-latest
            target: windows
            build_path: build/windows/x64/runner/Release
            asset_name: O3M-Windows.zip
            
          # macOS
          - os: macos-latest
            target: macos
            build_path: build/macos/Build/Products/Release
            asset_name: O3M-macOS.zip

          # Linux
          - os: ubuntu-latest
            target: linux
            build_path: build/linux/x64/release/bundle
            asset_name: O3M-Linux.tar.gz

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
  
      - name: Get Flutter Packages
        run: flutter pub get

      - name: Build Flutter Desktop App
        run: flutter build ${{ matrix.target }} --release

      - name: Compress Build (Windows)
        if: matrix.target == 'windows'
        run: Compress-Archive -Path "${{ matrix.build_path }}\*" -DestinationPath ${{ matrix.asset_name }}

      - name: Compress Build (macOS)
        if: matrix.target == 'macos'
        run: |
          cd ${{ matrix.build_path }}
          zip -r $GITHUB_WORKSPACE/${{ matrix.asset_name }} *.app

      - name: Compress Build (Linux)
        if: matrix.target == 'linux'
        run: |
          cd ${{ matrix.build_path }}
          tar -czvf $GITHUB_WORKSPACE/${{ matrix.asset_name }} *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
          draft: false
          prerelease: false